### ISSUE TITLE
DataError: value too long for type character varying(255)

### ISSUE THREAD

**Issue by mmclark** [SEED-platform/seed#111]
Error during matching, loading 2014 EPM Output for Upload file.

```
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/seed1.1/local/lib/python2.7/site-packages/celery/task/trace.py", line 233, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/ubuntu/.virtualenvs/seed1.1/local/lib/python2.7/site-packages/celery/task/trace.py", line 420, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/ubuntu/prj/seed/seed/decorators.py", line 59, in _wrapped
    response = fn(import_file_pk, *args, **kwargs)
  File "/home/ubuntu/prj/seed/seed/tasks.py", line 937, in _match_buildings
    results, i, can_rev_idx, unmatched_buildings, user_pk
  File "/home/ubuntu/prj/seed/seed/tasks.py", line 748, in handle_results
    can_snap_pk, building_pk, confidence=confidence, match_type=match_type
  File "/home/ubuntu/prj/seed/seed/models.py", line 359, in save_snapshot_match
    match_type=match_type
  File "/home/ubuntu/prj/seed/seed/mappings/mapper.py", line 117, in merge_building
    save_variant(snapshot, attr, can_attrs[attr])
  File "/home/ubuntu/prj/seed/seed/mappings/mapper.py", line 31, in save_variant
    value_source=data_source_id
  File "/home/ubuntu/.virtualenvs/seed1.1/local/lib/python2.7/site-packages/django/db/models/manager.py", line 154, in get_or_create
    return self.get_queryset().get_or_create(**kwargs)
  File "/home/ubuntu/.virtualenvs/seed1.1/local/lib/python2.7/site-packages/django/db/models/query.py", line 391, in get_or_create
    six.reraise(*exc_info)
  File "/home/ubuntu/.virtualenvs/seed1.1/local/lib/python2.7/site-packages/django/db/models/query.py", line 383, in get_or_create
    obj.save(force_insert=True, using=self.db)
  File "/home/ubuntu/.virtualenvs/seed1.1/local/lib/python2.7/site-packages/django/db/models/base.py", line 545, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/ubuntu/.virtualenvs/seed1.1/local/lib/python2.7/site-packages/django/db/models/base.py", line 573, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/home/ubuntu/.virtualenvs/seed1.1/local/lib/python2.7/site-packages/django/db/models/base.py", line 654, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/home/ubuntu/.virtualenvs/seed1.1/local/lib/python2.7/site-packages/django/db/models/base.py", line 687, in _do_insert
    using=using, raw=raw)
  File "/home/ubuntu/.virtualenvs/seed1.1/local/lib/python2.7/site-packages/django/db/models/manager.py", line 232, in _insert
    return insert_query(self.model, objs, fields, **kwargs)
  File "/home/ubuntu/.virtualenvs/seed1.1/local/lib/python2.7/site-packages/django/db/models/query.py", line 1514, in insert_query
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/home/ubuntu/.virtualenvs/seed1.1/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 903, in execute_sql
    cursor.execute(sql, params)
  File "/home/ubuntu/.virtualenvs/seed1.1/local/lib/python2.7/site-packages/django/db/backends/util.py", line 69, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/ubuntu/.virtualenvs/seed1.1/local/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/home/ubuntu/.virtualenvs/seed1.1/local/lib/python2.7/site-packages/django/db/utils.py", line 99, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/ubuntu/.virtualenvs/seed1.1/local/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
DataError: value too long for type character varying(255)
```

**Comment by carolinux** [comment]
well that looks like you're trying to put a larger string in a column in the db than is allowed (max 255 chars)

**Comment by aviveiros11** [comment]
Satisfied by #2553
