### ISSUE TITLE
PM file doesn't import all records

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#137]
Miles -- could you please look into why this Portfolio Manager file does not import all the records. In the gdrive issue folder for this issue, there is a doc describing the problem as well as sample files for importing. Please email me if you have questions.

**Comment by RDmitchell** [comment]
In the sample file with 100 records, there area very long fields, which I thought we fixed the import for:

* Property use detail alerts (951)
* Energy alerts (411)
* Data Center -- IT Energy Configuration (223)
* Property Notes (967)
* Water alerts (148)

**Comment by mmclark** [comment]
It looks like a potential problem with date handling/parsing:

'''
[2015-03-03 13:53:24,158: ERROR/MainProcess] Task seed.tasks.map_row_chunk[3b3b487b-b369-4bd2-9728-5ac58b305b94] raised exception: AttributeError("'int' object has no attribute 'read'",)
Traceback (most recent call last):
  File "/home/mmclark/.virtualenvs/seed/local/lib/python2.7/site-packages/celery/task/trace.py", line 233, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/mmclark/.virtualenvs/seed/local/lib/python2.7/site-packages/celery/task/trace.py", line 420, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/mmclark/git/seed/seed/tasks.py", line 504, in map_row_chunk
    **kwargs
  File "/home/mmclark/.virtualenvs/seed/src/mcm-core/mcm/mapper.py", line 186, in map_row
    apply_func=send_apply_func
  File "/home/mmclark/.virtualenvs/seed/src/mcm-core/mcm/mapper.py", line 112, in apply_column_value
    cleaned_value = cleaner.clean_value(value, column_name)
  File "/home/mmclark/.virtualenvs/seed/src/mcm-core/mcm/cleaners.py", line 90, in clean_value
    return date_cleaner(value)
  File "/home/mmclark/.virtualenvs/seed/src/mcm-core/mcm/cleaners.py", line 64, in date_cleaner
    dateutil.parser.parse(value)
  File "/home/mmclark/.virtualenvs/seed/src/python-dateutil/dateutil/parser.py", line 758, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/home/mmclark/.virtualenvs/seed/src/python-dateutil/dateutil/parser.py", line 310, in parse
    res, skipped_tokens = self._parse(timestr, **kwargs)
  File "/home/mmclark/.virtualenvs/seed/src/python-dateutil/dateutil/parser.py", line 376, in _parse
    l = _timelex.split(timestr)
  File "/home/mmclark/.virtualenvs/seed/src/python-dateutil/dateutil/parser.py", line 150, in split
    return list(cls(s))
  File "/home/mmclark/.virtualenvs/seed/src/python-dateutil/dateutil/parser.py", line 147, in next
    return self.__next__()  # Python 2.x support
  File "/home/mmclark/.virtualenvs/seed/src/python-dateutil/dateutil/parser.py", line 141, in __next__
    token = self.get_token()
  File "/home/mmclark/.virtualenvs/seed/src/python-dateutil/dateutil/parser.py", line 72, in get_token
    nextchar = self.instream.read(1)
AttributeError: 'int' object has no attribute 'read'
'''

**Comment by RDmitchell** [comment]
I don't think it is a date field problem. I took all the dates out of the CSV file that I made (see the file in the issue directory called NoDateFields), and I am still only getting 765 building records created, instead of 862.

**Comment by RDmitchell** [comment]
Turns out is IS a Date problem. 

The culprit is:

Year Ending -- Formatted as a date in Excel in the form of "12/31/2013" but it contains records that have integers such as "41639". 

So I believe that SEED interprets that field as a date (when importing as an Excel file), then finds some data not in the right format, and because it batches the record importing 100 records at a time, it throws out more than just the 12 records that have this problem.

If I change the 12 records that have the integer value to have 12/31/2013, the program successfully imports all 862 records.

So for now we have a workaround, ie, I can tell the cities to make sure that any Excel field that is formatted as a date has to have a date in it. 

In the long run, we need to figure out a way to flag the records that have this type of problems for the users so that they will know what is going on. And not batch the import in sets of 100 records.

**Comment by RDmitchell** [comment]
I will close this issue and turn the error catching long term goal into another issue.
