### ISSUE TITLE
Test cleanup

### ISSUE THREAD

**Issue by mmclark** [SEED-platform/seed#141]
Clean/comment out failing test to get to a "ground zero" of repeatably working tests.

**Comment by mmclark** [comment]
Checked in a new branch 'issue141_tests'.  One test was skipped, and 5 are failing.  Looks like an issue with py.test integration.  When running py.test, the 5 failing tests pass, and many others fail.

```
mmclark@canvas:~/git/seed$ workon seed
(seed)mmclark@canvas:~/git/seed$ export DJANGO_SETTINGS_MODULE=BE.settings.dev
(seed)mmclark@canvas:~/git/seed$ ./manage.py test
nosetests --exclude-dir=data_importer --verbosity=1
Creating test database for alias 'default'...
.....................................................................................................................................................................................................................S.....................EEEEE
======================================================================
ERROR: seed.common.tests.test_map.test_mapping_init
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mmclark/.virtualenvs/seed/local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
TypeError: test_mapping_init() takes exactly 1 argument (0 given)

======================================================================
ERROR: seed.common.tests.test_map.test_mapping_regex
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mmclark/.virtualenvs/seed/local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
TypeError: test_mapping_regex() takes exactly 1 argument (0 given)

======================================================================
ERROR: seed.common.tests.test_map.test_mapping_case
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mmclark/.virtualenvs/seed/local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
TypeError: test_mapping_case() takes exactly 1 argument (0 given)

======================================================================
ERROR: seed.common.tests.test_map.test_mapping_spc
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mmclark/.virtualenvs/seed/local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
TypeError: test_mapping_spc() takes exactly 1 argument (0 given)

======================================================================
ERROR: seed.common.tests.test_map.test_units
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mmclark/.virtualenvs/seed/local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
TypeError: test_units() takes exactly 1 argument (0 given)

----------------------------------------------------------------------
Ran 240 tests in 86.695s

FAILED (SKIP=1, errors=5)
Destroying test database for alias 'default'...

```

**Comment by mmclark** [comment]
After installing pytest-django and creating a pytest.ini file, these are the results of using the py.test runner:

```
39 failed, 187 passed, 1 warnings, 1 error in 67.52 seconds
```

**Comment by mmclark** [comment]
Quick note - setting the ONLY_HTTPS environment variable may be helpful in getting the tests to run correctly:

```
$ export ONLY_HTTPS=False
```

**Comment by RDmitchell** [comment]
These have been resolved and I am closing the issue
