### ISSUE TITLE
get_api_request_user in seed/utils/api.py fails with UnboundLocalError when HTTP_AUTHORIZATION is not basic

### ISSUE THREAD

**Issue by jackastner** [SEED-platform/seed#1414]
When I try to make an API call that does not use Basic HTTP_AUTHORIZATION, I get an internal server error (response status 500) stating that "local variable 'User' referenced before assignment". This presumably isn't mean to be the case since it's my fault for not providing correct authentication making a 401 more appropriate. 

Full error as printed by the server:

```
Internal Server Error: /api/v2/datasets/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 140, in get_response
    response = middleware_method(request, callback, callback_args, callback_kwargs)
  File "/home/john/ClearlyEnergy/seed/seed/utils/api.py", line 206, in process_view
    # pylint:disable=unused-argument
  File "/home/john/ClearlyEnergy/seed/seed/utils/api.py", line 187, in get_api_request_user
    return False
UnboundLocalError: local variable 'User' referenced before assignment
[10/Jul/2017 07:14:58] "POST /api/v2/datasets/?organization_id=1 HTTP/1.1" 500 11352
```

**Comment by nllong** [comment]
is this still an issue with current develop branch?
