### ISSUE TITLE
Swagger Django Errors

### ISSUE THREAD

**Issue by axelstudios** [SEED-platform/seed#2232]
### Expected Behavior
Loading the Swagger page should be error-free

### Actual Behavior
It doesn't appear to have any impact on the user, but loading the Swagger page results in a large amount of backend errors

<details>
  <summary>Errors</summary>
  <pre>
view's PropertyViewSet raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this
Traceback (most recent call last):
  File "/home/bldadmin/.local/lib/python3.6/site-packages/drf_yasg/inspectors/base.py", line 50, in call_view_method
    return view_method()
  File "/home/bldadmin/.local/lib/python3.6/site-packages/rest_framework/generics.py", line 66, in get_queryset
    % self.__class__.__name__
AssertionError: 'PropertyViewSet' should either include a `queryset` attribute, or override the `get_queryset()` method.
view's PropertyViewSet raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this
Traceback (most recent call last):
  File "/home/bldadmin/.local/lib/python3.6/site-packages/drf_yasg/inspectors/base.py", line 50, in call_view_method
    return view_method()
  File "/home/bldadmin/.local/lib/python3.6/site-packages/rest_framework/generics.py", line 66, in get_queryset
    % self.__class__.__name__
AssertionError: 'PropertyViewSet' should either include a `queryset` attribute, or override the `get_queryset()` method.
view's PropertyViewSet raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this
Traceback (most recent call last):
  File "/home/bldadmin/.local/lib/python3.6/site-packages/drf_yasg/inspectors/base.py", line 50, in call_view_method
    return view_method()
  File "/home/bldadmin/.local/lib/python3.6/site-packages/rest_framework/generics.py", line 66, in get_queryset
    % self.__class__.__name__
AssertionError: 'PropertyViewSet' should either include a `queryset` attribute, or override the `get_queryset()` method.
view's TaxLotViewSet raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this
Traceback (most recent call last):
  File "/home/bldadmin/.local/lib/python3.6/site-packages/drf_yasg/inspectors/base.py", line 50, in call_view_method
    return view_method()
  File "/home/bldadmin/.local/lib/python3.6/site-packages/rest_framework/generics.py", line 66, in get_queryset
    % self.__class__.__name__
AssertionError: 'TaxLotViewSet' should either include a `queryset` attribute, or override the `get_queryset()` method.
view's TaxLotViewSet raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this
Traceback (most recent call last):
  File "/home/bldadmin/.local/lib/python3.6/site-packages/drf_yasg/inspectors/base.py", line 50, in call_view_method
    return view_method()
  File "/home/bldadmin/.local/lib/python3.6/site-packages/rest_framework/generics.py", line 66, in get_queryset
    % self.__class__.__name__
AssertionError: 'TaxLotViewSet' should either include a `queryset` attribute, or override the `get_queryset()` method.
view's TaxLotViewSet raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this
Traceback (most recent call last):
  File "/home/bldadmin/.local/lib/python3.6/site-packages/drf_yasg/inspectors/base.py", line 50, in call_view_method
    return view_method()
  File "/home/bldadmin/.local/lib/python3.6/site-packages/rest_framework/generics.py", line 66, in get_queryset
    % self.__class__.__name__
AssertionError: 'TaxLotViewSet' should either include a `queryset` attribute, or override the `get_queryset()` method.
view's TaxLotViewSet raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this
Traceback (most recent call last):
  File "/home/bldadmin/.local/lib/python3.6/site-packages/drf_yasg/inspectors/base.py", line 50, in call_view_method
    return view_method()
  File "/home/bldadmin/.local/lib/python3.6/site-packages/rest_framework/generics.py", line 66, in get_queryset
    % self.__class__.__name__
AssertionError: 'TaxLotViewSet' should either include a `queryset` attribute, or override the `get_queryset()` method.
view's PropertyViewSet raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this
Traceback (most recent call last):
  File "/home/bldadmin/.local/lib/python3.6/site-packages/drf_yasg/inspectors/base.py", line 50, in call_view_method
    return view_method()
  File "/home/bldadmin/.local/lib/python3.6/site-packages/rest_framework/generics.py", line 66, in get_queryset
    % self.__class__.__name__
AssertionError: 'PropertyViewSet' should either include a `queryset` attribute, or override the `get_queryset()` method.
view's PropertyViewSet raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this
Traceback (most recent call last):
  File "/home/bldadmin/.local/lib/python3.6/site-packages/drf_yasg/inspectors/base.py", line 50, in call_view_method
    return view_method()
  File "/home/bldadmin/.local/lib/python3.6/site-packages/rest_framework/generics.py", line 66, in get_queryset
    % self.__class__.__name__
AssertionError: 'PropertyViewSet' should either include a `queryset` attribute, or override the `get_queryset()` method.
view's PropertyViewSet raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this
Traceback (most recent call last):
  File "/home/bldadmin/.local/lib/python3.6/site-packages/drf_yasg/inspectors/base.py", line 50, in call_view_method
    return view_method()
  File "/home/bldadmin/.local/lib/python3.6/site-packages/rest_framework/generics.py", line 66, in get_queryset
    % self.__class__.__name__
AssertionError: 'PropertyViewSet' should either include a `queryset` attribute, or override the `get_queryset()` method.
view's TaxLotViewSet raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this
Traceback (most recent call last):
  File "/home/bldadmin/.local/lib/python3.6/site-packages/drf_yasg/inspectors/base.py", line 50, in call_view_method
    return view_method()
  File "/home/bldadmin/.local/lib/python3.6/site-packages/rest_framework/generics.py", line 66, in get_queryset
    % self.__class__.__name__
AssertionError: 'TaxLotViewSet' should either include a `queryset` attribute, or override the `get_queryset()` method.
view's TaxLotViewSet raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this
Traceback (most recent call last):
  File "/home/bldadmin/.local/lib/python3.6/site-packages/drf_yasg/inspectors/base.py", line 50, in call_view_method
    return view_method()
  File "/home/bldadmin/.local/lib/python3.6/site-packages/rest_framework/generics.py", line 66, in get_queryset
    % self.__class__.__name__
AssertionError: 'TaxLotViewSet' should either include a `queryset` attribute, or override the `get_queryset()` method.
view's TaxLotViewSet raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this
Traceback (most recent call last):
  File "/home/bldadmin/.local/lib/python3.6/site-packages/drf_yasg/inspectors/base.py", line 50, in call_view_method
    return view_method()
  File "/home/bldadmin/.local/lib/python3.6/site-packages/rest_framework/generics.py", line 66, in get_queryset
    % self.__class__.__name__
AssertionError: 'TaxLotViewSet' should either include a `queryset` attribute, or override the `get_queryset()` method.
view's TaxLotViewSet raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this
Traceback (most recent call last):
  File "/home/bldadmin/.local/lib/python3.6/site-packages/drf_yasg/inspectors/base.py", line 50, in call_view_method
    return view_method()
  File "/home/bldadmin/.local/lib/python3.6/site-packages/rest_framework/generics.py", line 66, in get_queryset
    % self.__class__.__name__
AssertionError: 'TaxLotViewSet' should either include a `queryset` attribute, or override the `get_queryset()` method.
view's TaxLotViewSet raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this
Traceback (most recent call last):
  File "/home/bldadmin/.local/lib/python3.6/site-packages/drf_yasg/inspectors/base.py", line 50, in call_view_method
    return view_method()
  File "/home/bldadmin/.local/lib/python3.6/site-packages/rest_framework/generics.py", line 66, in get_queryset
    % self.__class__.__name__
AssertionError: 'TaxLotViewSet' should either include a `queryset` attribute, or override the `get_queryset()` method.
view's TaxLotViewSet raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this
Traceback (most recent call last):
  File "/home/bldadmin/.local/lib/python3.6/site-packages/drf_yasg/inspectors/base.py", line 50, in call_view_method
    return view_method()
  File "/home/bldadmin/.local/lib/python3.6/site-packages/rest_framework/generics.py", line 66, in get_queryset
    % self.__class__.__name__
AssertionError: 'TaxLotViewSet' should either include a `queryset` attribute, or override the `get_queryset()` method.
view's PropertyViewSet raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this
Traceback (most recent call last):
  File "/home/bldadmin/.local/lib/python3.6/site-packages/drf_yasg/inspectors/base.py", line 50, in call_view_method
    return view_method()
  File "/home/bldadmin/.local/lib/python3.6/site-packages/rest_framework/generics.py", line 66, in get_queryset
    % self.__class__.__name__
AssertionError: 'PropertyViewSet' should either include a `queryset` attribute, or override the `get_queryset()` method.
view's PropertyViewSet raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this
Traceback (most recent call last):
  File "/home/bldadmin/.local/lib/python3.6/site-packages/drf_yasg/inspectors/base.py", line 50, in call_view_method
    return view_method()
  File "/home/bldadmin/.local/lib/python3.6/site-packages/rest_framework/generics.py", line 66, in get_queryset
    % self.__class__.__name__
AssertionError: 'PropertyViewSet' should either include a `queryset` attribute, or override the `get_queryset()` method.
view's PropertyViewSet raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this
Traceback (most recent call last):
  File "/home/bldadmin/.local/lib/python3.6/site-packages/drf_yasg/inspectors/base.py", line 50, in call_view_method
    return view_method()
  File "/home/bldadmin/.local/lib/python3.6/site-packages/rest_framework/generics.py", line 66, in get_queryset
    % self.__class__.__name__
AssertionError: 'PropertyViewSet' should either include a `queryset` attribute, or override the `get_queryset()` method.
view's PropertyViewSet raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this
Traceback (most recent call last):
  File "/home/bldadmin/.local/lib/python3.6/site-packages/drf_yasg/inspectors/base.py", line 50, in call_view_method
    return view_method()
  File "/home/bldadmin/.local/lib/python3.6/site-packages/rest_framework/generics.py", line 66, in get_queryset
    % self.__class__.__name__
AssertionError: 'PropertyViewSet' should either include a `queryset` attribute, or override the `get_queryset()` method.
view's TaxLotViewSet raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this
Traceback (most recent call last):
  File "/home/bldadmin/.local/lib/python3.6/site-packages/drf_yasg/inspectors/base.py", line 50, in call_view_method
    return view_method()
  File "/home/bldadmin/.local/lib/python3.6/site-packages/rest_framework/generics.py", line 66, in get_queryset
    % self.__class__.__name__
AssertionError: 'TaxLotViewSet' should either include a `queryset` attribute, or override the `get_queryset()` method.
view's TaxLotViewSet raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this
Traceback (most recent call last):
  File "/home/bldadmin/.local/lib/python3.6/site-packages/drf_yasg/inspectors/base.py", line 50, in call_view_method
    return view_method()
  File "/home/bldadmin/.local/lib/python3.6/site-packages/rest_framework/generics.py", line 66, in get_queryset
    % self.__class__.__name__
AssertionError: 'TaxLotViewSet' should either include a `queryset` attribute, or override the `get_queryset()` method.
view's TaxLotViewSet raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this
Traceback (most recent call last):
  File "/home/bldadmin/.local/lib/python3.6/site-packages/drf_yasg/inspectors/base.py", line 50, in call_view_method
    return view_method()
  File "/home/bldadmin/.local/lib/python3.6/site-packages/rest_framework/generics.py", line 66, in get_queryset
    % self.__class__.__name__
AssertionError: 'TaxLotViewSet' should either include a `queryset` attribute, or override the `get_queryset()` method.
view's TaxLotViewSet raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this
Traceback (most recent call last):
  File "/home/bldadmin/.local/lib/python3.6/site-packages/drf_yasg/inspectors/base.py", line 50, in call_view_method
    return view_method()
  File "/home/bldadmin/.local/lib/python3.6/site-packages/rest_framework/generics.py", line 66, in get_queryset
    % self.__class__.__name__
AssertionError: 'TaxLotViewSet' should either include a `queryset` attribute, or override the `get_queryset()` method.
view's TaxLotViewSet raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this
Traceback (most recent call last):
  File "/home/bldadmin/.local/lib/python3.6/site-packages/drf_yasg/inspectors/base.py", line 50, in call_view_method
    return view_method()
  File "/home/bldadmin/.local/lib/python3.6/site-packages/rest_framework/generics.py", line 66, in get_queryset
    % self.__class__.__name__
AssertionError: 'TaxLotViewSet' should either include a `queryset` attribute, or override the `get_queryset()` method.
view's TaxLotViewSet raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this
Traceback (most recent call last):
  File "/home/bldadmin/.local/lib/python3.6/site-packages/drf_yasg/inspectors/base.py", line 50, in call_view_method
    return view_method()
  File "/home/bldadmin/.local/lib/python3.6/site-packages/rest_framework/generics.py", line 66, in get_queryset
    % self.__class__.__name__
AssertionError: 'TaxLotViewSet' should either include a `queryset` attribute, or override the `get_queryset()` method.
view's PropertyViewSet raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this
Traceback (most recent call last):
  File "/home/bldadmin/.local/lib/python3.6/site-packages/drf_yasg/inspectors/base.py", line 50, in call_view_method
    return view_method()
  File "/home/bldadmin/.local/lib/python3.6/site-packages/rest_framework/generics.py", line 66, in get_queryset
    % self.__class__.__name__
AssertionError: 'PropertyViewSet' should either include a `queryset` attribute, or override the `get_queryset()` method.
view's PropertyViewSet raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this
Traceback (most recent call last):
  File "/home/bldadmin/.local/lib/python3.6/site-packages/drf_yasg/inspectors/base.py", line 50, in call_view_method
    return view_method()
  File "/home/bldadmin/.local/lib/python3.6/site-packages/rest_framework/generics.py", line 66, in get_queryset
    % self.__class__.__name__
AssertionError: 'PropertyViewSet' should either include a `queryset` attribute, or override the `get_queryset()` method.
'default' on schema for ChoiceField(choices=[(0, 'Favor New'), (1, 'Favor Existing')], default='Favor New') will not be set because to_representation raised an exception
Traceback (most recent call last):
  File "/home/bldadmin/.local/lib/python3.6/site-packages/drf_yasg/utils.py", line 497, in get_field_default
    default = field_value_to_representation(field, default)
  File "/home/bldadmin/.local/lib/python3.6/site-packages/drf_yasg/utils.py", line 461, in field_value_to_representation
    value = field.to_representation(value)
  File "/home/bldadmin/seed/seed/serializers/base.py", line 23, in to_representation
    return self._choices[obj]
KeyError: 'Favor New'
'default' on schema for ChoiceField(choices=[(0, 'Favor New'), (1, 'Favor Existing')], default='Favor New') will not be set because to_representation raised an exception
Traceback (most recent call last):
  File "/home/bldadmin/.local/lib/python3.6/site-packages/drf_yasg/utils.py", line 497, in get_field_default
    default = field_value_to_representation(field, default)
  File "/home/bldadmin/.local/lib/python3.6/site-packages/drf_yasg/utils.py", line 461, in field_value_to_representation
    value = field.to_representation(value)
  File "/home/bldadmin/seed/seed/serializers/base.py", line 23, in to_representation
    return self._choices[obj]
KeyError: 'Favor New'
'default' on schema for ChoiceField(choices=[(0, 'Favor New'), (1, 'Favor Existing')], default='Favor New') will not be set because to_representation raised an exception
Traceback (most recent call last):
  File "/home/bldadmin/.local/lib/python3.6/site-packages/drf_yasg/utils.py", line 497, in get_field_default
    default = field_value_to_representation(field, default)
  File "/home/bldadmin/.local/lib/python3.6/site-packages/drf_yasg/utils.py", line 461, in field_value_to_representation
    value = field.to_representation(value)
  File "/home/bldadmin/seed/seed/serializers/base.py", line 23, in to_representation
    return self._choices[obj]
KeyError: 'Favor New'
'default' on schema for ChoiceField(choices=[(0, 'Favor New'), (1, 'Favor Existing')], default='Favor New') will not be set because to_representation raised an exception
Traceback (most recent call last):
  File "/home/bldadmin/.local/lib/python3.6/site-packages/drf_yasg/utils.py", line 497, in get_field_default
    default = field_value_to_representation(field, default)
  File "/home/bldadmin/.local/lib/python3.6/site-packages/drf_yasg/utils.py", line 461, in field_value_to_representation
    value = field.to_representation(value)
  File "/home/bldadmin/seed/seed/serializers/base.py", line 23, in to_representation
    return self._choices[obj]
KeyError: 'Favor New'
'default' on schema for ChoiceField(choices=[(0, 'Favor New'), (1, 'Favor Existing')], default='Favor New') will not be set because to_representation raised an exception
Traceback (most recent call last):
  File "/home/bldadmin/.local/lib/python3.6/site-packages/drf_yasg/utils.py", line 497, in get_field_default
    default = field_value_to_representation(field, default)
  File "/home/bldadmin/.local/lib/python3.6/site-packages/drf_yasg/utils.py", line 461, in field_value_to_representation
    value = field.to_representation(value)
  File "/home/bldadmin/seed/seed/serializers/base.py", line 23, in to_representation
    return self._choices[obj]
KeyError: 'Favor New'
'default' on schema for ChoiceField(choices=[(0, 'Favor New'), (1, 'Favor Existing')], default='Favor New') will not be set because to_representation raised an exception
Traceback (most recent call last):
  File "/home/bldadmin/.local/lib/python3.6/site-packages/drf_yasg/utils.py", line 497, in get_field_default
    default = field_value_to_representation(field, default)
  File "/home/bldadmin/.local/lib/python3.6/site-packages/drf_yasg/utils.py", line 461, in field_value_to_representation
    value = field.to_representation(value)
  File "/home/bldadmin/seed/seed/serializers/base.py", line 23, in to_representation
    return self._choices[obj]
KeyError: 'Favor New'
'default' on schema for ChoiceField(choices=[(0, 'Favor New'), (1, 'Favor Existing')], default='Favor New') will not be set because to_representation raised an exception
Traceback (most recent call last):
  File "/home/bldadmin/.local/lib/python3.6/site-packages/drf_yasg/utils.py", line 497, in get_field_default
    default = field_value_to_representation(field, default)
  File "/home/bldadmin/.local/lib/python3.6/site-packages/drf_yasg/utils.py", line 461, in field_value_to_representation
    value = field.to_representation(value)
  File "/home/bldadmin/seed/seed/serializers/base.py", line 23, in to_representation
    return self._choices[obj]
KeyError: 'Favor New'
'default' on schema for ChoiceField(choices=[(0, 'Favor New'), (1, 'Favor Existing')], default='Favor New') will not be set because to_representation raised an exception
Traceback (most recent call last):
  File "/home/bldadmin/.local/lib/python3.6/site-packages/drf_yasg/utils.py", line 497, in get_field_default
    default = field_value_to_representation(field, default)
  File "/home/bldadmin/.local/lib/python3.6/site-packages/drf_yasg/utils.py", line 461, in field_value_to_representation
    value = field.to_representation(value)
  File "/home/bldadmin/seed/seed/serializers/base.py", line 23, in to_representation
    return self._choices[obj]
KeyError: 'Favor New'
'default' on schema for ChoiceField(choices=[(0, 'Favor New'), (1, 'Favor Existing')], default='Favor New') will not be set because to_representation raised an exception
Traceback (most recent call last):
  File "/home/bldadmin/.local/lib/python3.6/site-packages/drf_yasg/utils.py", line 497, in get_field_default
    default = field_value_to_representation(field, default)
  File "/home/bldadmin/.local/lib/python3.6/site-packages/drf_yasg/utils.py", line 461, in field_value_to_representation
    value = field.to_representation(value)
  File "/home/bldadmin/seed/seed/serializers/base.py", line 23, in to_representation
    return self._choices[obj]
KeyError: 'Favor New'
'default' on schema for ChoiceField(choices=[(0, 'Favor New'), (1, 'Favor Existing')], default='Favor New') will not be set because to_representation raised an exception
Traceback (most recent call last):
  File "/home/bldadmin/.local/lib/python3.6/site-packages/drf_yasg/utils.py", line 497, in get_field_default
    default = field_value_to_representation(field, default)
  File "/home/bldadmin/.local/lib/python3.6/site-packages/drf_yasg/utils.py", line 461, in field_value_to_representation
    value = field.to_representation(value)
  File "/home/bldadmin/seed/seed/serializers/base.py", line 23, in to_representation
    return self._choices[obj]
KeyError: 'Favor New'
'default' on schema for ChoiceField(choices=[(0, 'Favor New'), (1, 'Favor Existing')], default='Favor New') will not be set because to_representation raised an exception
Traceback (most recent call last):
  File "/home/bldadmin/.local/lib/python3.6/site-packages/drf_yasg/utils.py", line 497, in get_field_default
    default = field_value_to_representation(field, default)
  File "/home/bldadmin/.local/lib/python3.6/site-packages/drf_yasg/utils.py", line 461, in field_value_to_representation
    value = field.to_representation(value)
  File "/home/bldadmin/seed/seed/serializers/base.py", line 23, in to_representation
    return self._choices[obj]
KeyError: 'Favor New'
'default' on schema for ChoiceField(choices=[(0, 'Favor New'), (1, 'Favor Existing')], default='Favor New') will not be set because to_representation raised an exception
Traceback (most recent call last):
  File "/home/bldadmin/.local/lib/python3.6/site-packages/drf_yasg/utils.py", line 497, in get_field_default
    default = field_value_to_representation(field, default)
  File "/home/bldadmin/.local/lib/python3.6/site-packages/drf_yasg/utils.py", line 461, in field_value_to_representation
    value = field.to_representation(value)
  File "/home/bldadmin/seed/seed/serializers/base.py", line 23, in to_representation
    return self._choices[obj]
KeyError: 'Favor New'
'default' on schema for ChoiceField(choices=[(0, 'Favor New'), (1, 'Favor Existing')], default='Favor New') will not be set because to_representation raised an exception
Traceback (most recent call last):
  File "/home/bldadmin/.local/lib/python3.6/site-packages/drf_yasg/utils.py", line 497, in get_field_default
    default = field_value_to_representation(field, default)
  File "/home/bldadmin/.local/lib/python3.6/site-packages/drf_yasg/utils.py", line 461, in field_value_to_representation
    value = field.to_representation(value)
  File "/home/bldadmin/seed/seed/serializers/base.py", line 23, in to_representation
    return self._choices[obj]
KeyError: 'Favor New'
</pre>
</details>

### Steps to Reproduce
Browse to `/app/#/api/swagger`, check the Django console

**Comment by adrian-lara** [comment]
The fix for the KeyError is to change
```
merge_protection = ChoiceField(choices=Column.COLUMN_MERGE_PROTECTION, default='Favor New')
```
to
```
merge_protection = ChoiceField(choices=Column.COLUMN_MERGE_PROTECTION, default=Column.COLUMN_MERGE_FAVOR_NEW)
```
in the ColumnSerializer

**Comment by adrian-lara** [comment]
Nothing to test from user perspective.
