### ISSUE TITLE
Docker image doesn't persist TimescaleDB extension

### ISSUE THREAD

**Issue by paddatrapper** [SEED-platform/seed#2256]
When re-creating a docker image, the database doesn't come back correctly if TimescaleDB has been updated upstream.

### Actual Behavior

```
Traceback (most recent call last):                                                                                                                                                              
  File "./manage.py", line 14, in <module>                                                                                                                                                      
    execute_from_command_line(sys.argv)                                                                                                                                                         
  File "/usr/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line                                                                            
    utility.execute()                                                                                                                                                                           
  File "/usr/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute                                                                                              
    self.fetch_command(subcommand).run_from_argv(self.argv)                                                                                                                                     
  File "/usr/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv                                                                                            
    self.execute(*args, **cmd_options)                                                                                                                                                          
  File "/usr/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execute                                                                                                  
    output = self.handle(*args, **options)                                                                                                                                                      
  File "/usr/lib/python3.6/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)                                                          
  File "/usr/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 85, in handle
    connection.prepare_database()                                                               
  File "/usr/lib/python3.6/site-packages/django/contrib/gis/db/backends/postgis/base.py", line 25, in prepare_database
    with self.cursor() as cursor:                                                               
  File "/usr/lib/python3.6/site-packages/django/db/backends/base/base.py", line 256, in cursor
    return self._cursor()               
  File "/usr/lib/python3.6/site-packages/django/db/backends/base/base.py", line 233, in _cursor
    self.ensure_connection()                                                                                                                                                                    
  File "/usr/lib/python3.6/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()                              
  File "/usr/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/lib/python3.6/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()                              
  File "/usr/lib/python3.6/site-packages/django/db/backends/base/base.py", line 197, in connect
    self.init_connection_state()
  File "/usr/lib/python3.6/site-packages/django/db/backends/postgresql/base.py", line 211, in init_connection_state
    timezone_changed = self.ensure_timezone()
  File "/usr/lib/python3.6/site-packages/django/db/backends/postgresql/base.py", line 204, in ensure_timezone
    cursor.execute(self.ops.set_time_zone_sql(), [timezone_name])
django.db.utils.OperationalError: could not access file "$libdir/timescaledb-1.6.1": No such file or directory
```

### Steps to Reproduce

```
docker volume create seed_pgdata
docker volume create seed_media
docker-compose up
docker-compose kill
docker container prune
docker image prune
docker image rm (all the SEED related images)
docker-compose up
```

`ALTER EXTENSION timescaledb UPDATE;` returns:

```
ERROR:  extension "timescaledb" has no update path from version "1.6.1" to version "1.5.0"
```

**Comment by paddatrapper** [comment]
The solution is to upgrade the `timescaledb-postgresql-12` package in the postgres container... It seems to have an old version of the package by default.
