### ISSUE TITLE
AT BSync import error

### ISSUE THREAD

**Issue by macintoshpie** [SEED-platform/seed#2814]
When uploading the file below, and reading the "finalize mapping" page, SEED errors when trying to create the meters:

```python
seed_celery    | [2021-08-12 14:42:22,313: ERROR/ForkPoolWorker-1] Chord callback for '0229e8d3-dcfc-4aeb-b029-f477bf89a532' raised: ChordError('Dependency 42a11204-81ff-4031-901d-9299531d89c6 raised TypeError("float() argument must be a string or a number, not \'NoneType\'")')
seed_celery    | Traceback (most recent call last):
seed_celery    |   File "/usr/lib/python3.9/site-packages/celery/app/trace.py", line 385, in trace_task
seed_celery    |     R = retval = fun(*args, **kwargs)
seed_celery    |   File "/usr/lib/python3.9/site-packages/celery/app/trace.py", line 650, in __protected_call__
seed_celery    |     return self.run(*args, **kwargs)
seed_celery    |   File "/seed/seed/data_importer/tasks.py", line 1427, in _map_additional_models
seed_celery    |     p_status, property_state, property_view, messages = building_file.process(
seed_celery    |   File "/seed/seed/models/building_file.py", line 305, in process
seed_celery    |     readings = {
seed_celery    |   File "/seed/seed/models/building_file.py", line 309, in <setcomp>
seed_celery    |     reading=float(mr.get('reading', 0)) * meter_conversions.get(mr.get('source_unit'), 1.00),
seed_celery    | TypeError: float() argument must be a string or a number, not 'NoneType'
seed_celery    | 
seed_celery    | During handling of the above exception, another exception occurred:
seed_celery    | 
seed_celery    | Traceback (most recent call last):
seed_celery    |   File "/usr/lib/python3.9/site-packages/celery/backends/redis.py", line 406, in on_chord_part_return
seed_celery    |     callback.delay([unpack(tup, decode) for tup in resl])
seed_celery    |   File "/usr/lib/python3.9/site-packages/celery/backends/redis.py", line 406, in <listcomp>
seed_celery    |     callback.delay([unpack(tup, decode) for tup in resl])
seed_celery    |   File "/usr/lib/python3.9/site-packages/celery/backends/redis.py", line 359, in _unpack_chord_result
seed_celery    |     raise ChordError('Dependency {0} raised {1!r}'.format(tid, retval))
seed_celery    | celery.exceptions.ChordError: Dependency 42a11204-81ff-4031-901d-9299531d89c6 raised TypeError("float() argument must be a string or a number, not 'NoneType'")
seed_celery    | [2021-08-12 14:42:22,326: ERROR/ForkPoolWorker-1] Task seed.data_importer.tasks._map_additional_models[42a11204-81ff-4031-901d-9299531d89c6] raised unexpected: TypeError("float() argument must be a string or a number, not 'NoneType'")
seed_celery    | Traceback (most recent call last):
seed_celery    |   File "/usr/lib/python3.9/site-packages/celery/app/trace.py", line 385, in trace_task
seed_celery    |     R = retval = fun(*args, **kwargs)
seed_celery    |   File "/usr/lib/python3.9/site-packages/celery/app/trace.py", line 650, in __protected_call__
seed_celery    |     return self.run(*args, **kwargs)
seed_celery    |   File "/seed/seed/data_importer/tasks.py", line 1427, in _map_additional_models
seed_celery    |     p_status, property_state, property_view, messages = building_file.process(
seed_celery    |   File "/seed/seed/models/building_file.py", line 305, in process
seed_celery    |     readings = {
seed_celery    |   File "/seed/seed/models/building_file.py", line 309, in <setcomp>
seed_celery    |     reading=float(mr.get('reading', 0)) * meter_conversions.get(mr.get('source_unit'), 1.00),
seed_celery    | TypeError: float() argument must be a string or a number, not 'NoneType'
```

[buildings_xml_report (12) (1).xml.zip](https://github.com/SEED-platform/seed/files/6976327/buildings_xml_report.12.1.xml.zip)

**Comment by macintoshpie** [comment]
This `auc:ResourceUse` in the file seems to be our problem. It has no `ResourceUnits`
<img width="439" alt="Screen Shot 2021-08-12 at 10 50 16 AM" src="https://user-images.githubusercontent.com/18518728/129218354-6b2e00d1-46b8-491a-a2e8-685d30990bde.png">

In fact it doesn't even have an energy resource type, which means we should be skipping it anyways.
