### ISSUE TITLE
geojson package: simplejson error

### ISSUE THREAD

**Issue by macintoshpie** [SEED-platform/seed#2895]
## context
When updating SEED to Django 3.1, our testsuite started trying to run one of our management commands as a test: `create_geojson_test_data`. Note that the file has since been renamed to avoid this. But it would create this error when it would try to run the file:
```
======================================================================
ERROR: Failure: AttributeError (module 'simplejson' has no attribute 'JSONEncoder')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/usr/lib/python3.9/site-packages/nose/loader.py", line 417, in loadTestsFromName
    module = self.importer.importFromPath(
  File "/usr/lib/python3.9/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python3.9/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/usr/lib/python3.9/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/usr/lib/python3.9/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/seed/seed/management/commands/create_geojson_test_data.py", line 10, in <module>
    import geojson
  File "/usr/lib/python3.9/site-packages/geojson/__init__.py", line 1, in <module>
    from geojson.codec import dump, dumps, load, loads, GeoJSONEncoder
  File "/usr/lib/python3.9/site-packages/geojson/codec.py", line 11, in <module>
    class GeoJSONEncoder(json.JSONEncoder):
AttributeError: module 'simplejson' has no attribute 'JSONEncoder'
```

## task
- determine if this error is legitimate by running the command
- fix if needed

**Comment by nllong** [comment]
no longer relevant
