### ISSUE TITLE
XMLSchema fails to fetch gbXML Schema

### ISSUE THREAD

**Issue by macintoshpie** [SEED-platform/seed#2902]
## context
When running SEEDs automated tests, one of the tests which uses the BuildingSync schema to validate a file fails b/c the package XMLSchema fails to fetch the gbxml schema.
See [here](https://github.com/SEED-platform/seed/pull/2901/checks?check_run_id=3695819939) for the full logs (note that the FIRST error is the real issue -- all following ones are a result of this one.

EDIT: See https://github.com/BuildingSync/schema/issues/393 for more info

## task
- determine if this is a fluke or whether it's reproducible. Fix the issue if there is one and remove the skip flag for the test.

## logs snippet
```
/seed/seed/building_sync/building_sync.py:200: XMLSchemaImportWarning: Import of namespace 'http://www.gbxml.org/schema' from ['http://www.gbxml.org/schema/6-01/GreenBuildingXML_Ver6.01.xsd'] failed: <urlopen error cannot access to resource 'http://www.gbxml.org/schema/6-01/GreenBuildingXML_Ver6.01.xsd': Forbidden>.
  return xmlschema.XMLSchema(schema_path)
======================================================================
ERROR: test_build_bsyncr_input_returns_valid_bsync_document (seed.tests.test_analysis_pipelines.TestBsyncrPipeline)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/nose/case.py", line 134, in run
    self.runTest(result)
  File "/usr/lib/python3.9/site-packages/nose/case.py", line 152, in runTest
    test(result)
  File "/usr/lib/python3.9/site-packages/django/test/testcases.py", line 245, in __call__
    self._setup_and_call(result)
  File "/usr/lib/python3.9/site-packages/django/test/testcases.py", line 281, in _setup_and_call
    super().__call__(result)
  File "/usr/lib/python3.9/unittest/case.py", line 653, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib/python3.9/unittest/case.py", line 601, in run
    self._feedErrorsToResult(result, outcome.errors)
  File "/usr/lib/python3.9/unittest/case.py", line 519, in _feedErrorsToResult
    result.addError(test, exc_info)
  File "/usr/lib/python3.9/site-packages/nose/proxy.py", line 132, in addError
    self.result.addError(self.test, self._prepareErr(err))
  File "/usr/lib/python3.9/site-packages/nose/result.py", line 61, in addError
    exc_info = self._exc_info_to_string(err, test)
  File "/usr/lib/python3.9/site-packages/nose/result.py", line 187, in _exc_info_to_string
    return _TextTestResult._exc_info_to_string(self, err, test)
  File "/usr/lib/python3.9/unittest/result.py", line 185, in _exc_info_to_string
    tb_e = traceback.TracebackException(
  File "/usr/lib/python3.9/traceback.py", line 517, in __init__
    self.filename = exc_value.filename
AttributeError: 'XMLSchemaParseError' object has no attribute 'filename'
```

**Comment by nllong** [comment]
This is due to gbxml.org is now using https:// for the protocol. We need to update it in the schema and see if it breaks any of our tools...

**Comment by macintoshpie** [comment]
Update -- it seems to be out of our control right now. The gbXML folks are looking into fixing this.

**Comment by macintoshpie** [comment]
I've already updated the schemaLocation attribute in our schemas, we just need to go reenable the test now

**Comment by nllong** [comment]
> I've already updated the schemaLocation attribute in our schemas, we just need to go reenable the test now

@macintoshpie, are you going to reenable the test or do you want to toss that to someone else?

**Comment by macintoshpie** [comment]
I'm going to toss it to someone else 👀
