### ISSUE TITLE
Fix remaining resolve errors when launching SEED in develop mode

### ISSUE THREAD

**Issue by nllong** [SEED-platform/seed#3385]
There appear to be a few dangling render errors that exist, but only when SEED starts in non-debug mode. 

```
seed_web       | During handling of the above exception, another exception occurred:
seed_web       |
seed_web       | Traceback (most recent call last):
seed_web       |   File "/usr/lib/python3.9/site-packages/django/template/base.py", line 835, in _resolve_lookup
seed_web       |     if isinstance(current, BaseContext) and getattr(type(current), bit):
seed_web       | AttributeError: type object 'Context' has no attribute 'debug'
seed_web       |
seed_web       | During handling of the above exception, another exception occurred:
seed_web       |
seed_web       | Traceback (most recent call last):
seed_web       |   File "/usr/lib/python3.9/site-packages/django/template/base.py", line 843, in _resolve_lookup
seed_web       |     current = current[int(bit)]
seed_web       | ValueError: invalid literal for int() with base 10: 'debug'
seed_web       |
seed_web       | During handling of the above exception, another exception occurred:
seed_web       |
seed_web       | Traceback (most recent call last):
seed_web       |   File "/usr/lib/python3.9/site-packages/django/template/base.py", line 848, in _resolve_lookup
seed_web       |     raise VariableDoesNotExist("Failed lookup for key "
seed_web       | django.template.base.VariableDoesNotExist: Failed lookup for key [debug] in [{'True': True, 'False': False, 'None': None}, {'STATIC_URL': '/static/'}, {}, {}, {}, {}]
seed_web       | DEBUG:django.template:Exception while resolving variable 'debug' in template 'unknown'.
seed_web       | Traceback (most recent call last):
seed_web       |   File "/usr/lib/python3.9/site-packages/django/template/base.py", line 829, in _resolve_lookup
seed_web       |     current = current[bit]
seed_web       |   File "/usr/lib/python3.9/site-packages/django/template/context.py", line 83, in __getitem__
seed_web       |     raise KeyError(key)
seed_web       | KeyError: 'debug'
seed_web       |
seed_web       | During handling of the above exception, another exception occurred:
seed_web       |
seed_web       | Traceback (most recent call last):
seed_web       |   File "/usr/lib/python3.9/site-packages/django/template/base.py", line 835, in _resolve_lookup
seed_web       |     if isinstance(current, BaseContext) and getattr(type(current), bit):
seed_web       | AttributeError: type object 'Context' has no attribute 'debug'
seed_web       |
seed_web       | During handling of the above exception, another exception occurred:
seed_web       |
seed_web       | Traceback (most recent call last):
seed_web       |   File "/usr/lib/python3.9/site-packages/django/template/base.py", line 843, in _resolve_lookup
seed_web       |     current = current[int(bit)]
```

**Comment by RDmitchell** [comment]
@nllong -- this got closed automatically -- is this all fixed?

**Comment by nllong** [comment]
yeah, this only impacts developers. So I think leaving it closed makes sense.
