### ISSUE TITLE
seedtest -- Upload failed -- new dialog box

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#453]
![image](https://cloud.githubusercontent.com/assets/6314950/10649124/246e132c-77f7-11e5-8ed2-e9aea4734d4b.png)

Getting these error messages

24angular.js:12477 TypeError: s.is_initial_state is not a function
    at fn0 (eval at <anonymous> (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.7/angular.js:13322:15), <anonymous>:4:483)
    at Object.expressionInputWatch [as get] (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.7/angular.js:14302:31)
    at Scope.$digest (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.7/angular.js:15818:40)
    at Scope.$apply (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.7/angular.js:16097:24)
    at HTMLAnchorElement.<anonymous> (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.7/angular.js:23554:23)
    at HTMLAnchorElement.p.event.dispatch (https://ajax.googleapis.com/ajax/libs/jquery/1.8.0/jquery.min.js:2:37944)
    at HTMLAnchorElement.g.handle.h (https://ajax.googleapis.com/ajax/libs/jquery/1.8.0/jquery.min.js:2:33881)(anonymous function) @ angular.js:12477(anonymous function) @ angular.js:9246Scope.$digest @ angular.js:15844Scope.$apply @ angular.js:16097(anonymous function) @ angular.js:23554p.event.dispatch @ jquery.min.js:2g.handle.h @ jquery.min.js:2
12angular.js:12477 TypeError: s.is_initial_state is not a function
    at fn0 (eval at <anonymous> (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.7/angular.js:13322:15), <anonymous>:4:483)
    at Object.expressionInputWatch [as get] (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.7/angular.js:14302:31)
    at Scope.$digest (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.7/angular.js:15818:40)
    at Scope.$apply (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.7/angular.js:16097:24)
    at https://ajax.googleapis.com/ajax/libs/angularjs/1.4.7/angular.js:17864:36
    at completeOutstandingRequest (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.7/angular.js:5507:10)
    at https://ajax.googleapis.com/ajax/libs/angularjs/1.4.7/angular.js:5784:7(anonymous function) @ angular.js:12477(anonymous function) @ angular.js:9246Scope.$digest @ angular.js:15844Scope.$apply @ angular.js:16097(anonymous function) @ angular.js:17864completeOutstandingRequest @ angular.js:5507(anonymous function) @ angular.js:5784
24angular.js:12477 TypeError: s.is_initial_state is not a function
    at fn0 (eval at <anonymous> (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.7/angular.js:13322:15), <anonymous>:4:483)
    at Object.expressionInputWatch [as get] (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.7/angular.js:14302:31)
    at Scope.$digest (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.7/angular.js:15818:40)
    at Scope.$apply (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.7/angular.js:16097:24)
    at $$debounceViewValueCommit (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.7/angular.js:25388:14)
    at $setViewValue (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.7/angular.js:25360:12)
    at HTMLInputElement.listener (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.7/angular.js:21679:12)
    at HTMLInputElement.p.event.dispatch (https://ajax.googleapis.com/ajax/libs/jquery/1.8.0/jquery.min.js:2:37944)
    at HTMLInputElement.g.handle.h (https://ajax.googleapis.com/ajax/libs/jquery/1.8.0/jquery.min.js:2:33881)(anonymous function) @ angular.js:12477(anonymous function) @ angular.js:9246Scope.$digest @ angular.js:15844Scope.$apply @ angular.js:16097$$debounceViewValueCommit @ angular.js:25388$setViewValue @ angular.js:25360listener @ angular.js:21679p.event.dispatch @ jquery.min.js:2g.handle.h @ jquery.min.js:2
12angular.js:12477 TypeError: s.is_initial_state is not a function
    at fn0 (eval at <anonymous> (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.7/angular.js:13322:15), <anonymous>:4:483)
    at Object.expressionInputWatch [as get] (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.7/angular.js:14302:31)
    at Scope.$digest (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.7/angular.js:15818:40)
    at Scope.$apply (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.7/angular.js:16097:24)
    at HTMLButtonElement.<anonymous> (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.7/angular.js:23554:23)
    at HTMLButtonElement.p.event.dispatch (https://ajax.googleapis.com/ajax/libs/jquery/1.8.0/jquery.min.js:2:37944)
    at HTMLButtonElement.g.handle.h (https://ajax.googleapis.com/ajax/libs/jquery/1.8.0/jquery.min.js:2:33881)(anonymous function) @ angular.js:12477(anonymous function) @ angular.js:9246Scope.$digest @ angular.js:15844Scope.$apply @ angular.js:16097(anonymous function) @ angular.js:23554p.event.dispatch @ jquery.min.js:2g.handle.h @ jquery.min.js:2
12angular.js:12477 TypeError: s.is_initial_state is not a function
    at fn0 (eval at <anonymous> (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.7/angular.js:13322:15), <anonymous>:4:483)
    at Object.expressionInputWatch [as get] (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.7/angular.js:14302:31)
    at Scope.$digest (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.7/angular.js:15818:40)
    at Scope.$apply (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.7/angular.js:16097:24)
    at done (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.7/angular.js:10546:47)
    at completeRequest (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.7/angular.js:10744:7)
    at XMLHttpRequest.requestLoaded (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.7/angular.js:10685:9)(anonymous function) @ angular.js:12477(anonymous function) @ angular.js:9246Scope.$digest @ angular.js:15844Scope.$apply @ angular.js:16097done @ angular.js:10546completeRequest @ angular.js:10744requestLoaded @ angular.js:10685
angular.js:12477 ProgressController is now deprecated. Use UibProgressController instead.
angular.js:12477 progressbar is now deprecated. Use uib-progressbar instead.
12angular.js:12477 TypeError: s.is_initial_state is not a function
    at fn0 (eval at <anonymous> (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.7/angular.js:13322:15), <anonymous>:4:483)
    at Object.expressionInputWatch [as get] (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.7/angular.js:14302:31)
    at Scope.$digest (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.7/angular.js:15818:40)
    at Scope.$apply (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.7/angular.js:16097:24)
    at done (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.7/angular.js:10546:47)
    at completeRequest (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.7/angular.js:10744:7)
    at XMLHttpRequest.requestLoaded (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.7/angular.js:10685:9)(anonymous function) @ angular.js:12477(anonymous function) @ angular.js:9246Scope.$digest @ angular.js:15844Scope.$apply @ angular.js:16097done @ angular.js:10546completeRequest @ angular.js:10744requestLoaded @ angular.js:10685
12angular.js:12477 TypeError: s.is_initial_state is not a function
    at fn0 (eval at <anonymous> (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.7/angular.js:13322:15), <anonymous>:4:483)
    at Object.expressionInputWatch [as get] (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.7/angular.js:14302:31)
    at Scope.$digest (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.7/angular.js:15818:40)
    at https://ajax.googleapis.com/ajax/libs/angularjs/1.4.7/angular.js:16028:26
    at completeOutstandingRequest (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.7/angular.js:5507:10)
    at https://ajax.googleapis.com/ajax/libs/angularjs/1.4.7/angular.js:5784:7(anonymous function) @ angular.js:12477(anonymous function) @ angular.js:9246Scope.$digest @ angular.js:15844(anonymous function) @ angular.js:16028completeOutstandingRequest @ angular.js:5507(anonymous function) @ angular.js:5784
24angular.js:12477 TypeError: s.is_initial_state is not a function
    at fn0 (eval at <anonymous> (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.7/angular.js:13322:15), <anonymous>:4:483)
    at Object.expressionInputWatch [as get] (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.7/angular.js:14302:31)
    at Scope.$digest (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.7/angular.js:15818:40)
    at Scope.$apply (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.7/angular.js:16097:24)
    at Scope.$scope.uploaderfunc (https://seedtest.s3.amazonaws.com/seed/js/controllers/data_upload_modal_ctrl.js:190:20)
    at fn (eval at <anonymous> (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.7/angular.js:13322:15), <anonymous>:4:449)
    at Scope.destination.(anonymous function) [as eventfunc] (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.7/angular.js:8880:22)
    at qq.s3.FineUploader.callbacks.onSubmitted (https://seedtest.s3.amazonaws.com/seed/js/directives/beUploader.js:103:19)
    at safeCallback (https://seedtest.s3.amazonaws.com/vendors/bower_components/fine-uploader/_build/s3.fineuploader.js:2449:33)
    at self._options.callbacks.(anonymous function) (https://seedtest.s3.amazonaws.com/vendors/bower_components/fine-uploader/_build/s3.fineuploader.js:2462:28)(anonymous function) @ angular.js:12477(anonymous function) @ angular.js:9246Scope.$digest @ angular.js:15844Scope.$apply @ angular.js:16097$scope.uploaderfunc @ data_upload_modal_ctrl.js:190fn @ VM912:4destination.(anonymous function) @ angular.js:8880qq.s3.FineUploader.callbacks.onSubmitted @ beUploader.js:103safeCallback @ s3.fineuploader.js:2449self._options.callbacks.(anonymous function) @ s3.fineuploader.js:2462qq.basePrivateApi._onSubmitCallbackSuccess @ s3.fineuploader.js:2214(anonymous function) @ s3.fineuploader.js:528qq.basePrivateApi._handleCheckedCallback @ s3.fineuploader.js:1664qq.basePrivateApi._upload @ s3.fineuploader.js:2187qq.basePrivateApi._onValidateCallbackSuccess @ s3.fineuploader.js:2268(anonymous function) @ s3.fineuploader.js:528qq.basePrivateApi._handleCheckedCallback @ s3.fineuploader.js:1664qq.basePrivateApi._onValidateBatchCallbackSuccess @ s3.fineuploader.js:2241(anonymous function) @ s3.fineuploader.js:528qq.basePrivateApi._handleCheckedCallback @ s3.fineuploader.js:1664qq.basePrivateApi._prepareItemsForUpload @ s3.fineuploader.js:2165qq.uiPrivateApi._prepareItemsForUpload @ s3.fineuploader.js:3460qq.basePublicApi.addFiles @ s3.fineuploader.js:1452qq.basePrivateApi._onInputChange @ s3.fineuploader.js:2025qq.UploadButton.onChange @ s3.fineuploader.js:1699(anonymous function) @ s3.fineuploader.js:1069
s3.fineuploader.js:3847 POST https://seedtest.lbl.gov/data/sign_policy_document/ 403 (FORBIDDEN)sendRequest @ s3.fineuploader.js:3847send @ s3.fineuploader.js:3977getSignature @ s3.fineuploader.js:5595(anonymous function) @ s3.fineuploader.js:528qq.s3.util.qq.s3.util.generateAwsParams @ s3.fineuploader.js:4951generateAwsParams @ s3.fineuploader.js:6598prepareForSend @ s3.fineuploader.js:6632handleSimpleUpload @ s3.fineuploader.js:6579handleUpload @ s3.fineuploader.js:6391(anonymous function) @ s3.fineuploader.js:6554then @ s3.fineuploader.js:917handleStartUploadSignal @ s3.fineuploader.js:6551publicApi.upload @ s3.fineuploader.js:4405api.upload @ s3.fineuploader.js:4101qq.basePrivateApi._onSubmitCallbackSuccess @ s3.fineuploader.js:2217(anonymous function) @ s3.fineuploader.js:528qq.basePrivateApi._handleCheckedCallback @ s3.fineuploader.js:1664qq.basePrivateApi._upload @ s3.fineuploader.js:2187qq.basePrivateApi._onValidateCallbackSuccess @ s3.fineuploader.js:2268(anonymous function) @ s3.fineuploader.js:528qq.basePrivateApi._handleCheckedCallback @ s3.fineuploader.js:1664qq.basePrivateApi._onValidateBatchCallbackSuccess @ s3.fineuploader.js:2241(anonymous function) @ s3.fineuploader.js:528qq.basePrivateApi._handleCheckedCallback @ s3.fineuploader.js:1664qq.basePrivateApi._prepareItemsForUpload @ s3.fineuploader.js:2165qq.uiPrivateApi._prepareItemsForUpload @ s3.fineuploader.js:3460qq.basePublicApi.addFiles @ s3.fineuploader.js:1452qq.basePrivateApi._onInputChange @ s3.fineuploader.js:2025qq.UploadButton.onChange @ s3.fineuploader.js:1699(anonymous function) @ s3.fineuploader.js:1069
s3.fineuploader.js:169 [FineUploader 3.9.1] POST request for 0 has failed - response code 403qq.log @ s3.fineuploader.js:169qq.basePublicApi.log @ s3.fineuploader.js:1314options.log @ s3.fineuploader.js:1728onComplete @ s3.fineuploader.js:3772(anonymous function) @ s3.fineuploader.js:3875
s3.fineuploader.js:169 [FineUploader 3.9.1] Error attempting to parse signature response: SyntaxError: Unexpected token <qq.log @ s3.fineuploader.js:169qq.basePublicApi.log @ s3.fineuploader.js:1314options.log @ s3.fineuploader.js:1728handleSignatureReceived @ s3.fineuploader.js:5521onComplete @ s3.fineuploader.js:3775(anonymous function) @ s3.fineuploader.js:3875
s3.fineuploader.js:169 [FineUploader 3.9.1] Received an empty or invalid response from the server!qq.log @ s3.fineuploader.js:169qq.basePublicApi.log @ s3.fineuploader.js:1314options.log @ s3.fineuploader.js:1728handleSignatureReceived @ s3.fineuploader.js:5550onComplete @ s3.fineuploader.js:3775(anonymous function) @ s3.fineuploader.js:3875
s3.fineuploader.js:169 [FineUploader 3.9.1] Policy signing failed.  Received an empty or invalid response from the server!qq.log @ s3.fineuploader.js:169qq.basePublicApi.log @ s3.fineuploader.js:1314options.log @ s3.fineuploader.js:1728(anonymous function) @ s3.fineuploader.js:4961(anonymous function) @ s3.fineuploader.js:959qq.each @ s3.fineuploader.js:491failure @ s3.fineuploader.js:958handleSignatureReceived @ s3.fineuploader.js:5553onComplete @ s3.fineuploader.js:3775(anonymous function) @ s3.fineuploader.js:3875
s3.fineuploader.js:3847 POST https://seedtest.lbl.gov/data/sign_policy_document/ 403 (FORBIDDEN)sendRequest @ s3.fineuploader.js:3847send @ s3.fineuploader.js:3977getSignature @ s3.fineuploader.js:5595(anonymous function) @ s3.fineuploader.js:528qq.s3.util.qq.s3.util.generateAwsParams @ s3.fineuploader.js:4951generateAwsParams @ s3.fineuploader.js:6598prepareForSend @ s3.fineuploader.js:6632handleSimpleUpload @ s3.fineuploader.js:6579handleUpload @ s3.fineuploader.js:6391handleStartUploadSignal @ s3.fineuploader.js:6546publicApi.upload @ s3.fineuploader.js:4405api.retry @ s3.fineuploader.js:4110(anonymous function) @ s3.fineuploader.js:2071
s3.fineuploader.js:169 [FineUploader 3.9.1] POST request for 0 has failed - response code 403qq.log @ s3.fineuploader.js:169qq.basePublicApi.log @ s3.fineuploader.js:1314options.log @ s3.fineuploader.js:1728onComplete @ s3.fineuploader.js:3772(anonymous function) @ s3.fineuploader.js:3875
s3.fineuploader.js:169 [FineUploader 3.9.1] Error attempting to parse signature response: SyntaxError: Unexpected token <qq.log @ s3.fineuploader.js:169qq.basePublicApi.log @ s3.fineuploader.js:1314options.log @ s3.fineuploader.js:1728handleSignatureReceived @ s3.fineuploader.js:5521onComplete @ s3.fineuploader.js:3775(anonymous function) @ s3.fineuploader.js:3875
s3.fineuploader.js:169 [FineUploader 3.9.1] Received an empty or invalid response from the server!qq.log @ s3.fineuploader.js:169qq.basePublicApi.log @ s3.fineuploader.js:1314options.log @ s3.fineuploader.js:1728handleSignatureReceived @ s3.fineuploader.js:5550onComplete @ s3.fineuploader.js:3775(anonymous function) @ s3.fineuploader.js:3875
s3.fineuploader.js:169 [FineUploader 3.9.1] Policy signing failed.  Received an empty or invalid response from the server!qq.log @ s3.fineuploader.js:169qq.basePublicApi.log @ s3.fineuploader.js:1314options.log @ s3.fineuploader.js:1728(anonymous function) @ s3.fineuploader.js:4961(anonymous function) @ s3.fineuploader.js:959qq.each @ s3.fineuploader.js:491failure @ s3.fineuploader.js:958handleSignatureReceived @ s3.fineuploader.js:5553onComplete @ s3.fineuploader.js:3775(anonymous function) @ s3.fineuploader.js:3875
s3.fineuploader.js:3847 POST https://seedtest.lbl.gov/data/sign_policy_document/ 403 (FORBIDDEN)sendRequest @ s3.fineuploader.js:3847send @ s3.fineuploader.js:3977getSignature @ s3.fineuploader.js:5595(anonymous function) @ s3.fineuploader.js:528qq.s3.util.qq.s3.util.generateAwsParams @ s3.fineuploader.js:4951generateAwsParams @ s3.fineuploader.js:6598prepareForSend @ s3.fineuploader.js:6632handleSimpleUpload @ s3.fineuploader.js:6579handleUpload @ s3.fineuploader.js:6391handleStartUploadSignal @ s3.fineuploader.js:6546publicApi.upload @ s3.fineuploader.js:4405api.retry @ s3.fineuploader.js:4110(anonymous function) @ s3.fineuploader.js:2071
s3.fineuploader.js:169 [FineUploader 3.9.1] POST request for 0 has failed - response code 403qq.log @ s3.fineuploader.js:169qq.basePublicApi.log @ s3.fineuploader.js:1314options.log @ s3.fineuploader.js:1728onComplete @ s3.fineuploader.js:3772(anonymous function) @ s3.fineuploader.js:3875
s3.fineuploader.js:169 [FineUploader 3.9.1] Error attempting to parse signature response: SyntaxError: Unexpected token <qq.log @ s3.fineuploader.js:169qq.basePublicApi.log @ s3.fineuploader.js:1314options.log @ s3.fineuploader.js:1728handleSignatureReceived @ s3.fineuploader.js:5521onComplete @ s3.fineuploader.js:3775(anonymous function) @ s3.fineuploader.js:3875
s3.fineuploader.js:169 [FineUploader 3.9.1] Received an empty or invalid response from the server!qq.log @ s3.fineuploader.js:169qq.basePublicApi.log @ s3.fineuploader.js:1314options.log @ s3.fineuploader.js:1728handleSignatureReceived @ s3.fineuploader.js:5550onComplete @ s3.fineuploader.js:3775(anonymous function) @ s3.fineuploader.js:3875
s3.fineuploader.js:169 [FineUploader 3.9.1] Policy signing failed.  Received an empty or invalid response from the server!qq.log @ s3.fineuploader.js:169qq.basePublicApi.log @ s3.fineuploader.js:1314options.log @ s3.fineuploader.js:1728(anonymous function) @ s3.fineuploader.js:4961(anonymous function) @ s3.fineuploader.js:959qq.each @ s3.fineuploader.js:491failure @ s3.fineuploader.js:958handleSignatureReceived @ s3.fineuploader.js:5553onComplete @ s3.fineuploader.js:3775(anonymous function) @ s3.fineuploader.js:3875
s3.fineuploader.js:3847 POST https://seedtest.lbl.gov/data/sign_policy_document/ 403 (FORBIDDEN)sendRequest @ s3.fineuploader.js:3847send @ s3.fineuploader.js:3977getSignature @ s3.fineuploader.js:5595(anonymous function) @ s3.fineuploader.js:528qq.s3.util.qq.s3.util.generateAwsParams @ s3.fineuploader.js:4951generateAwsParams @ s3.fineuploader.js:6598prepareForSend @ s3.fineuploader.js:6632handleSimpleUpload @ s3.fineuploader.js:6579handleUpload @ s3.fineuploader.js:6391handleStartUploadSignal @ s3.fineuploader.js:6546publicApi.upload @ s3.fineuploader.js:4405api.retry @ s3.fineuploader.js:4110(anonymous function) @ s3.fineuploader.js:2071
s3.fineuploader.js:169 [FineUploader 3.9.1] POST request for 0 has failed - response code 403qq.log @ s3.fineuploader.js:169qq.basePublicApi.log @ s3.fineuploader.js:1314options.log @ s3.fineuploader.js:1728onComplete @ s3.fineuploader.js:3772(anonymous function) @ s3.fineuploader.js:3875
s3.fineuploader.js:169 [FineUploader 3.9.1] Error attempting to parse signature response: SyntaxError: Unexpected token <qq.log @ s3.fineuploader.js:169qq.basePublicApi.log @ s3.fineuploader.js:1314options.log @ s3.fineuploader.js:1728handleSignatureReceived @ s3.fineuploader.js:5521onComplete @ s3.fineuploader.js:3775(anonymous function) @ s3.fineuploader.js:3875
s3.fineuploader.js:169 [FineUploader 3.9.1] Received an empty or invalid response from the server!qq.log @ s3.fineuploader.js:169qq.basePublicApi.log @ s3.fineuploader.js:1314options.log @ s3.fineuploader.js:1728handleSignatureReceived @ s3.fineuploader.js:5550onComplete @ s3.fineuploader.js:3775(anonymous function) @ s3.fineuploader.js:3875
s3.fineuploader.js:169 [FineUploader 3.9.1] Policy signing failed.  Received an empty or invalid response from the server!qq.log @ s3.fineuploader.js:169qq.basePublicApi.log @ s3.fineuploader.js:1314options.log @ s3.fineuploader.js:1728(anonymous function) @ s3.fineuploader.js:4961(anonymous function) @ s3.fineuploader.js:959qq.each @ s3.fineuploader.js:491failure @ s3.fineuploader.js:958handleSignatureReceived @ s3.fineuploader.js:5553onComplete @ s3.fineuploader.js:3775(anonymous function) @ s3.fineuploader.js:3875
36angular.js:12477 TypeError: s.is_initial_state is not a function
    at fn0 (eval at <anonymous> (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.7/angular.js:13322:15), <anonymous>:4:483)
    at Object.expressionInputWatch [as get] (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.7/angular.js:14302:31)
    at Scope.$digest (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.7/angular.js:15818:40)
    at Scope.$apply (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.7/angular.js:16097:24)
    at Scope.$scope.uploaderfunc (https://seedtest.s3.amazonaws.com/seed/js/controllers/data_upload_modal_ctrl.js:190:20)
    at fn (eval at <anonymous> (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.7/angular.js:13322:15), <anonymous>:4:449)
    at Scope.destination.(anonymous function) [as eventfunc] (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.7/angular.js:8880:22)
    at qq.s3.FineUploader.callbacks.onProgress (https://seedtest.s3.amazonaws.com/seed/js/directives/beUploader.js:146:19)
    at safeCallback (https://seedtest.s3.amazonaws.com/vendors/bower_components/fine-uploader/_build/s3.fineuploader.js:2449:33)
    at Object.self._options.callbacks.(anonymous function) [as onProgress] (https://seedtest.s3.amazonaws.com/vendors/bower_components/fine-uploader/_build/s3.fineuploader.js:2462:28)(anonymous function) @ angular.js:12477(anonymous function) @ angular.js:9246Scope.$digest @ angular.js:15844Scope.$apply @ angular.js:16097$scope.uploaderfunc @ data_upload_modal_ctrl.js:190fn @ VM912:4destination.(anonymous function) @ angular.js:8880qq.s3.FineUploader.callbacks.onProgress @ beUploader.js:146safeCallback @ s3.fineuploader.js:2449self._options.callbacks.(anonymous function) @ s3.fineuploader.js:2462options.onProgress @ s3.fineuploader.js:1732uploadCompleted @ s3.fineuploader.js:6457(anonymous function) @ s3.fineuploader.js:6648(anonymous function) @ s3.fineuploader.js:959qq.each @ s3.fineuploader.js:491failure @ s3.fineuploader.js:958(anonymous function) @ s3.fineuploader.js:4962(anonymous function) @ s3.fineuploader.js:959qq.each @ s3.fineuploader.js:491failure @ s3.fineuploader.js:958handleSignatureReceived @ s3.fineuploader.js:5553onComplete @ s3.fineuploader.js:3775(anonymous function) @ s3.fineuploader.js:3875

**Comment by RDmitchell** [comment]
Actually this seems to be happening with any file. Thought it was working earlier, but maybe I am wrong.

**Comment by danielmcquillen** [comment]
This will be fixed tomorrow when Miles updates seedtest with the latest develop (which merges my FixAngularUpdateIssues branch)

**Comment by RDmitchell** [comment]
closing this
