### ISSUE TITLE
Data Cleansing Report not working

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#459]
Assigned to @nllong 

When I click on the Data Cleansing Report button in mapping, I get the error messages below. In the UI, nothing happens (ie, no error, and no display of the data cleansing dialog box).

This is on seedtest. I was using the Data Cleansing file that Claudine made, but I think it will happen with any file. Here is a link to the file
https://drive.google.com/open?id=0B3fTKpZ9Dx7LNnA4Y1hfcmVqZkE

Below is the error message set:

12angular.js:12477 TypeError: s.is_initial_state is not a function
    at fn0 (eval at <anonymous> (https://seedtest.s3.amazonaws.com/vendors/bower_components/angular/angular.js:13322:15), <anonymous>:4:483)
    at Object.expressionInputWatch [as get] (https://seedtest.s3.amazonaws.com/vendors/bower_components/angular/angular.js:14302:31)
    at Scope.$digest (https://seedtest.s3.amazonaws.com/vendors/bower_components/angular/angular.js:15818:40)
    at Scope.$apply (https://seedtest.s3.amazonaws.com/vendors/bower_components/angular/angular.js:16097:24)
    at HTMLButtonElement.<anonymous> (https://seedtest.s3.amazonaws.com/vendors/bower_components/angular/angular.js:23554:23)
    at HTMLButtonElement.p.event.dispatch (https://ajax.googleapis.com/ajax/libs/jquery/1.8.0/jquery.min.js:2:37944)
    at HTMLButtonElement.g.handle.h (https://ajax.googleapis.com/ajax/libs/jquery/1.8.0/jquery.min.js:2:33881)(anonymous function) @ angular.js:12477(anonymous function) @ angular.js:9246Scope.$digest @ angular.js:15844Scope.$apply @ angular.js:16097(anonymous function) @ angular.js:23554p.event.dispatch @ jquery.min.js:2g.handle.h @ jquery.min.js:2
angular.js:10722 GET https://seedtest.lbl.gov/cleansing/results/?import_file_id=1741 500 (INTERNAL SERVER ERROR)(anonymous function) @ angular.js:10722sendReq @ angular.js:10515serverRequest @ angular.js:10222processQueue @ angular.js:14745(anonymous function) @ angular.js:14761Scope.$eval @ angular.js:15989Scope.$digest @ angular.js:15800Scope.$apply @ angular.js:16097(anonymous function) @ angular.js:23554p.event.dispatch @ jquery.min.js:2g.handle.h @ jquery.min.js:2
12angular.js:12477 TypeError: s.is_initial_state is not a function
    at fn0 (eval at <anonymous> (https://seedtest.s3.amazonaws.com/vendors/bower_components/angular/angular.js:13322:15), <anonymous>:4:483)
    at Object.expressionInputWatch [as get] (https://seedtest.s3.amazonaws.com/vendors/bower_components/angular/angular.js:14302:31)
    at Scope.$digest (https://seedtest.s3.amazonaws.com/vendors/bower_components/angular/angular.js:15818:40)
    at Scope.$apply (https://seedtest.s3.amazonaws.com/vendors/bower_components/angular/angular.js:16097:24)
    at done (https://seedtest.s3.amazonaws.com/vendors/bower_components/angular/angular.js:10546:47)
    at completeRequest (https://seedtest.s3.amazonaws.com/vendors/bower_components/angular/angular.js:10744:7)
    at XMLHttpRequest.requestLoaded (https://seedtest.s3.amazonaws.com/vendors/bower_components/angular/angular.js:10685:9)

**Comment by nllong** [comment]
This can be closed as it has been merged. There is another PR out but it is cosmetic.
