### ISSUE TITLE
Bug loading program setup

### ISSUE THREAD

**Issue by perryr16** [SEED-platform/seed#4785]
Navigating to Program Setup thows an erorr.

dev1
```
vendors.ce4e0bdd2670.js:21 Error: [$injector:unpr] http://errors.angularjs.org/1.8.3/$injector/unpr?p0=%24uibModalInstanceProvider%20%3C-%20%24uibModalInstance%20%3C-%20program_setup_controller
    at vendors.ce4e0bdd2670.js:8:173919
    at vendors.ce4e0bdd2670.js:16:468
    at Object.d [as get] (vendors.ce4e0bdd2670.js:15:7898)
    at vendors.ce4e0bdd2670.js:16:530
    at d (vendors.ce4e0bdd2670.js:15:7898)
    at e (vendors.ce4e0bdd2670.js:15:8139)
    at Object.instantiate (vendors.ce4e0bdd2670.js:15:8540)
    at vendors.ce4e0bdd2670.js:20:778
    at Object.<anonymous> (vendors.ce4e0bdd2670.js:33:107754)
    at vendors.ce4e0bdd2670.js:13:134 '<div ui-view="" class="ui-view-container" data-ng-animate="1">'
```

local with develop
```
angular.js:15697 Error: [$injector:unpr] Unknown provider: $uibModalInstanceProvider <- $uibModalInstance <- program_setup_controller
https://errors.angularjs.org/1.8.3/$injector/unpr?p0=%24uibModalInstanceProvider%20%3C-%20%24uibModalInstance%20%3C-%20program_setup_controller
    at angular.js:138:12
    at angular.js:4991:19
    at Object.getService [as get] (angular.js:5151:32)
    at angular.js:4996:45
    at getService (angular.js:5151:32)
    at injectionArgs (angular.js:5176:58)
    at Object.instantiate (angular.js:5220:18)
    at $controller (angular.js:11829:28)
    at Object.<anonymous> (angular-ui-router.min.js:11:107114)
    at angular.js:1391:18 '<div ui-view="" class="ui-view-container ng-scope" data-ng-animate="1">'
```

**Comment by perryr16** [comment]
Program setup is a modal typically accessed from the insights pages via "Program Configuration", however the Program Setup link under (+) directs users to a new page. I

s this link necessary? The program configuration modal makes this link redundant. It can't be both a modal and a page.
