### ISSUE TITLE
The same user can be added to an organization multiple times

### ISSUE THREAD

**Issue by mmclark** [SEED-platform/seed#54]
The same user can be added to an organization multiple times, after which the system throws a MultipleObjectsReturned error:

Internal Server Error: /app/accounts/get_organizations/
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/seed1.1/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, _callback_args, *_callback_kwargs)
  File "/home/ubuntu/prj/seed/seed/utils/api.py", line 91, in _wrapped
    return fn(request, _args, *_kwargs)
  File "/home/ubuntu/.virtualenvs/seed1.1/local/lib/python2.7/site-packages/annoying/decorators.py", line 164, in wrapper
    response = func(request, _args, *_kwargs)
  File "/home/ubuntu/.virtualenvs/seed1.1/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, _args, *_kwargs)
  File "/home/ubuntu/prj/seed/seed/views/accounts.py", line 151, in get_organizations
    return {'organizations': _dict_org(request, qs)}
  File "/home/ubuntu/prj/seed/seed/views/accounts.py", line 61, in _dict_org
    organization=o, user=request.user)
  File "/home/ubuntu/.virtualenvs/seed1.1/local/lib/python2.7/site-packages/django/db/models/manager.py", line 151, in get
    return self.get_queryset().get(_args, *_kwargs)
  File "/home/ubuntu/.virtualenvs/seed1.1/local/lib/python2.7/site-packages/django/db/models/query.py", line 313, in get
    (self.model._meta.object_name, num))
MultipleObjectsReturned: get() returned more than one OrganizationUser -- it returned 2!

**Comment by axelstudios** [comment]
No longer an issue
