### ISSUE TITLE
AttributeError: 'int' object has no attribute 'strip'

### ISSUE THREAD

**Issue by mmclark** [SEED-platform/seed#603]
Found in output of celery on seedtest.  Putting here so we can follow up.

```
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/seed1.2/local/lib/python2.7/site-packages/celery/backends/base.py", line 565, in on_chord_part_return
    ret = j(timeout=3.0, propagate=propagate)
  File "/home/ubuntu/.virtualenvs/seed1.2/local/lib/python2.7/site-packages/celery/result.py", line 691, in join_native
    raise value
AttributeError: 'int' object has no attribute 'strip'
[2015-12-18 12:44:11,726: ERROR/MainProcess] Task seed.tasks.map_row_chunk[35f09492-af8f-46f0-87f0-4ceb00065c27] raised unexpected: AttributeError("'int' object has no attribute 'strip'",)
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/seed1.2/local/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/ubuntu/.virtualenvs/seed1.2/local/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/ubuntu/prj/seed/seed/tasks.py", line 556, in map_row_chunk
    model.tax_lot_id = _normalize_tax_lot_id(model.tax_lot_id)
  File "/home/ubuntu/prj/seed/seed/tasks.py", line 490, in _normalize_tax_lot_id
    return value.strip().lstrip('0').upper().replace(
AttributeError: 'int' object has no attribute 'strip'
```

**Comment by RDmitchell** [comment]
@pipermerriam -- this is referencing "normalize_tax_lot_id" -- is this something you should look into?

**Comment by pipermerriam** [comment]
bork, easy to fix. I'll get a PR in asap.

**Comment by axelstudios** [comment]
No longer an issue
