### ISSUE TITLE
Admin/Superuser Delete Buildings not working

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#684]
If I log into seedtest with my superuser account, so that I can see all the organizations, when I click on the red DELETE BUILDINGS button, the program doesn't do anything. There don't appear to be any error messages.

I tried logging in with an incognito window and it didn't make any difference. Incognito + browser refresh = same result of no movement in deleting the buildings. 

Also, it took almost 2 minutes for the program to display the list of organizations at the bottom of the screen (!!)

In the example below, I clicked on the Delete Buildings button for LBNL 77, and the program turned the button into a gray progress bar, but then never actually made any progress. This can sometimes take a long time, but now it isn't even starting. 
![image](https://cloud.githubusercontent.com/assets/6314950/12624987/94d2c1bc-c4e6-11e5-82be-b1996467322e.png)

**Comment by StephenCzarnecki** [comment]
Seems like this has something to do with changing celery to use json instead of pickle in https://github.com/SEED-platform/seed/commit/2631c66bdd7382e35c79dea887dc36833e31503f

In short at that commit (and currently it seems) celery gives an error about something not being JSON serializable.

Prior to that commit the admin deleting function seems to work.  At that commit I get the following errror in celery when I try to do an admin "Remove Buildings":

```
[2016-01-29 15:45:13,541: ERROR/MainProcess] Task seed.tasks._delete_organization_buildings[0d4d0f2a-b8ef-48fd-b837-fec9a8ba2ee4] raised unexpected: EncodeError(TypeError('[17557, 17558] is not JSON serializable',),)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/vagrant/seed/seed/decorators.py", line 63, in _wrapped
    response = fn(import_file_pk, *args, **kwargs)
  File "/home/vagrant/seed/seed/tasks.py", line 1526, in _delete_organization_buildings
    _delete_canonical_buildings.delay(can_ids)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/task.py", line 453, in delay
    return self.apply_async(args, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/task.py", line 559, in apply_async
    **dict(self._get_exec_options(), **options)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/base.py", line 353, in send_task
    reply_to=reply_to or self.oid, **options
  File "/usr/local/lib/python2.7/dist-packages/celery/app/amqp.py", line 305, in publish_task
    **kwargs
  File "/usr/local/lib/python2.7/dist-packages/kombu/messaging.py", line 165, in publish
    compression, headers)
  File "/usr/local/lib/python2.7/dist-packages/kombu/messaging.py", line 241, in _prepare
    body) = dumps(body, serializer=serializer)
  File "/usr/local/lib/python2.7/dist-packages/kombu/serialization.py", line 164, in dumps
    payload = encoder(data)
  File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python2.7/dist-packages/kombu/serialization.py", line 59, in _reraise_errors
    reraise(wrapper, wrapper(exc), sys.exc_info()[2])
  File "/usr/local/lib/python2.7/dist-packages/kombu/serialization.py", line 55, in _reraise_errors
    yield
  File "/usr/local/lib/python2.7/dist-packages/kombu/serialization.py", line 164, in dumps
    payload = encoder(data)
  File "/usr/local/lib/python2.7/dist-packages/anyjson/__init__.py", line 141, in dumps
    return implementation.dumps(value)
  File "/usr/local/lib/python2.7/dist-packages/anyjson/__init__.py", line 87, in dumps
    return self._encode(data)
  File "/usr/local/lib/python2.7/dist-packages/simplejson/__init__.py", line 354, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/lib/python2.7/dist-packages/simplejson/encoder.py", line 262, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python2.7/dist-packages/simplejson/encoder.py", line 340, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python2.7/dist-packages/simplejson/encoder.py", line 239, in default
    raise TypeError(repr(o) + " is not JSON serializable")
EncodeError: [17557, 17558] is not JSON serializable
```

That same error also appears when I try to do an admin remove buildings on the current head of develop.  It is odd that the error seems to be saying that a list of numbers is not json serializable since that seems like it should be a very basic case.

**Comment by RDmitchell** [comment]
@nllong -- we need to fix this because right now we can't delete buildings as superuser, which is a problem, even for testing on seedtest.

**Comment by StephenCzarnecki** [comment]
Actually I take back what I said about the error message being the same.  The message is the same but the call stack looks a little different on the current head of develop.  The one on the head of develop has a line referencing /home/vagrant/seed/seed/serializers/celery.py.

Here it is for reference:

```

[2016-01-29 16:17:48,511: ERROR/MainProcess] Task seed.tasks._delete_organization_buildings[71c610ff-1e00-41ee-bbba-d314cb481455] raised unexpected: EncodeError(TypeError('[17545, 17546, 17547] is not JSON serializable',),)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/vagrant/seed/seed/decorators.py", line 63, in _wrapped
    response = fn(import_file_pk, *args, **kwargs)
  File "/home/vagrant/seed/seed/tasks.py", line 1489, in _delete_organization_buildings
    _delete_canonical_buildings.delay(can_ids)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/task.py", line 453, in delay
    return self.apply_async(args, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/task.py", line 559, in apply_async
    **dict(self._get_exec_options(), **options)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/base.py", line 353, in send_task
    reply_to=reply_to or self.oid, **options
  File "/usr/local/lib/python2.7/dist-packages/celery/app/amqp.py", line 305, in publish_task
    **kwargs
  File "/usr/local/lib/python2.7/dist-packages/kombu/messaging.py", line 165, in publish
    compression, headers)
  File "/usr/local/lib/python2.7/dist-packages/kombu/messaging.py", line 241, in _prepare
    body) = dumps(body, serializer=serializer)
  File "/usr/local/lib/python2.7/dist-packages/kombu/serialization.py", line 164, in dumps
    payload = encoder(data)
  File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python2.7/dist-packages/kombu/serialization.py", line 59, in _reraise_errors
    reraise(wrapper, wrapper(exc), sys.exc_info()[2])
  File "/usr/local/lib/python2.7/dist-packages/kombu/serialization.py", line 55, in _reraise_errors
    yield
  File "/usr/local/lib/python2.7/dist-packages/kombu/serialization.py", line 164, in dumps
    payload = encoder(data)
  File "/home/vagrant/seed/seed/serializers/celery.py", line 32, in seed_dumps
    return json.dumps(obj, cls=CeleryDatetimeSerializer)
  File "/usr/lib/python2.7/json/__init__.py", line 250, in dumps
    sort_keys=sort_keys, **kw).encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "/home/vagrant/seed/seed/serializers/celery.py", line 20, in default
    return json.JSONEncoder.default(self, obj)
  File "/usr/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
EncodeError: [17545, 17546, 17547] is not JSON serializable
```

**Comment by StephenCzarnecki** [comment]
More things I was wrong about:  The thing that is being failed to serialize is not a list of ints.  It is a django.db.models.query.ValuesListQuerySet

**Comment by nllong** [comment]
did this not fix it: https://github.com/SEED-platform/seed/commit/0ccbc18b323d275d18da20eb84ef8baa533a0066

**Comment by StephenCzarnecki** [comment]
No, at least not that I can tell.  Looking into adding a branch in CeleryDateTimeSerializer that is basically

elif isinstance(obj, QuerySet):
    #use django.core.serializers.serialize

**Comment by nllong** [comment]
is there an easy way for me to recreate your issue locally?

**Comment by StephenCzarnecki** [comment]
First:  Looks like using django's serializer won't work since it wants a QuerySet and not a ValuesListQuerySet.

@nllong Yes, easily.  To reproduce the issue locally just sign into an admin account the go Profile (little gear at the top-left)->Admin.  Scroll down to the bottom to the "Remove all buildings from an organization" section.  Pick an org with some buildings and click the red "Remove Buildings" button.  After you click the conformation box the page should go into a progress bar that never moves.  The app should just do a bunch of "[29/Jan/2016 17:10:49] "POST /app/progress/ HTTP/1.1" 200 38" messages and the celery output should give you the error.

**Comment by nllong** [comment]
I think the easiest thing to do is typecast to a list instead of a value_list. Celery is only going to take the basic object types. 

Here is a branch that worked locally on my machine.
https://github.com/SEED-platform/seed/tree/684-list-typecast

**Comment by StephenCzarnecki** [comment]
@RDmitchell  I just did a quick check and the branch from @nllong seems to fix the issue locally for me too.

**Comment by RDmitchell** [comment]
Great, I'll test on seedtest when it gets there. thx

**Comment by RDmitchell** [comment]
I can now delete buildings as a superuser. Thanks !

**Comment by RDmitchell** [comment]
I may have spoken too soon. It seems like the delete buildings feature is working, but in the end, it doesn't seem like it finishes. 

I left it running for 45+ minutes for one of my test accounts on seedtest, and it still doesn't seem to have updated the progress bar -- it should say "success" in the little red progress bar, but it doesn't -- and it doesn't seem to actually have hit the complete right hand side of the space the progress bar fills. And the stripes are still "moving", which I think is meant to imply that it is still working. Maybe it really is still working because there were so many records, but I have my doubts? 

Not sure how to proceed. I think I will hand it back to Stephen to do some detective work.

**Comment by RDmitchell** [comment]
![image](https://cloud.githubusercontent.com/assets/6314950/12762641/166b11bc-c9a5-11e5-8d46-c6d5adc97fd0.png)

**Comment by RDmitchell** [comment]
I refreshed the browser, went back to LBNL 8, clicked "Remove Buildings" and the program sped through the progress bar (because I think all the buildings were deleted), and then displayed the "success" message on the progress bar. So the records seem to be deleted, but for whatever reason the progress bar isn't updating properly. 

![image](https://cloud.githubusercontent.com/assets/6314950/12762920/8588b288-c9a6-11e5-9adc-e32a5aa165ad.png)

**Comment by RDmitchell** [comment]
Because this seems to be more-or-less working, and it is so far a functionality only I really need (for the production instance of seed) I have set the Priority = 2, although I would like this to get cleaned up at some point in the not too distant future. thx !

**Comment by RDmitchell** [comment]
on a new (relatively clean) user account, when I went to delete buildings, the program deleted the records (591) and reported the "success" message on the progress bar. So I'm not sure what causes the program not to appear to finish the delete.

![image](https://cloud.githubusercontent.com/assets/6314950/12771759/86325844-c9e0-11e5-93a8-ee6cf35a23ee.png)

**Comment by RDmitchell** [comment]
@nicholasserra -- am assigning this to you, priority = 3 -- if/when you get to this, I might need to set up a case on seedtest that you can use Sentry to figure out what is going on. I am setting this to March (not Feb release).

**Comment by nicholasserra** [comment]
@RDmitchell So what's the final issue on this? From what I understand some visual cue isn't triggering that it's done?

**Comment by RDmitchell** [comment]
@mmclark -- I guess you need to set Nick up as a superuser on seedtest so that he can see what's going on with this? 
@nicholasserra -- once you are a superuser, I can point you to an organization to try deleting buildings on -- I think it has to do with the number of records. It finishes properly if there aren't too many records to delete, but seems to have issues when there has been a lot of data importing, deleting, data reimporting by me, the user, in an organization.

**Comment by mmclark** [comment]
Sorry for the delay - @nicholasserra is now a superuser on seedtest

**Comment by RDmitchell** [comment]
thanks @mmclark  !

**Comment by nicholasserra** [comment]
So I tested deleting buildings for that org with 10,000 of them, and it took a while, but worked. It refreshed and had zero buildings. I think the issue here is that I just need to speed all this stuff up.

![screen shot 2016-02-12 at 3 02 06 pm](https://cloud.githubusercontent.com/assets/512288/13018848/0b9edf0a-d19a-11e5-9511-c8283aa3052d.png)

**Comment by nicholasserra** [comment]
Also, it probably seems to lag, because to refresh the UI it needs to load all the orgs again, which takes minutes. So fixing #747 will probably fix this.

**Comment by nicholasserra** [comment]
Reassigning for testing, i'd like to see if my fix in #748 resolves this.

**Comment by RDmitchell** [comment]
I think this is working, it is just very slow.

**Comment by RDmitchell** [comment]
I am going to do a few mores tests with large data files (if I can ever get them to load) but in the meantime, I am going to close this issue and declare it ready for production, because I was able to finally delete (and the progress reported Success properly) a large and somewhat problematic (maybe) set of records
