### ISSUE TITLE
Bubble up celery matching errors to user

### ISSUE THREAD

**Issue by nicholasserra** [SEED-platform/seed#763]
Errors in matching simply halt the match, instead do some error handling and show user a message.

```
[2016-02-17 11:23:15,385: ERROR/MainProcess] Task seed.tasks._match_buildings[1964faa5-cfba-421b-882d-a1a3431a065f] raised unexpected: UnboundLocalError("local variable 'normalized_address' referenced before assignment",)
Traceback (most recent call last):
  File "/Users/nick/.virtualenvs/seed-new/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/Users/nick/.virtualenvs/seed-new/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/Users/nick/Code/seed/seed/decorators.py", line 63, in _wrapped
    response = fn(import_file_pk, *args, **kwargs)
  File "/Users/nick/Code/seed/seed/tasks.py", line 1302, in _match_buildings
    _normalize_address_str(unmatched[4]) for unmatched in unmatched_buildings
  File "/Users/nick/Code/seed/seed/tasks.py", line 1236, in _normalize_address_str
    return normalized_address.lower().strip()
UnboundLocalError: local variable 'normalized_address' referenced before assignment
```

**Comment by nllong** [comment]
Celery and background tasks have been cleaned up significantly. Recreate this issue if we encounter again.
