### ISSUE TITLE
"NoneType object is not iterable" in _match_buildings

### ISSUE THREAD

**Issue by mmclark** [SEED-platform/seed#873]
Seen in the celery log on the seed-timeseries instance:

```
[2016-03-24 20:50:22,786: ERROR/MainProcess] Task seed.tasks._match_buildings[b08a550f-b526-4805-a23f-901207f6bc5a] raised unexpected: TypeError("'NoneType' object is not iterable",)
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/seed/local/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/ubuntu/.virtualenvs/seed/local/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/ubuntu/seed/seed/decorators.py", line 62, in _wrapped
    response = fn(import_file_pk, *args, **kwargs)
  File "/home/ubuntu/seed/seed/tasks.py", line 1375, in _match_buildings
    results, i, can_rev_idx, unmatched_buildings, user_pk
  File "/home/ubuntu/seed/seed/tasks.py", line 916, in handle_results
    default_pk=building_pk,
TypeError: 'NoneType' object is not iterable
[2016-03-24 20:50:30,163: INFO/MainProcess] Task seed.tasks._match_buildings[4a3dd051-1f5a-4b5a-9089-d01786ae1a93] succeeded in 244.049537786s: {'status': 'success', 'progress': 100, 'progress_key': u':1:SEED:_match_buildings:PROG:107'}
```

**Comment by RDmitchell** [comment]
This might have been me trying to unmatch some records in the matching screen. It seemed to put the program into endless spinner mode, which is why I had @mmclark restart the ts instance.

**Comment by RDmitchell** [comment]
This would have been for the SEED App Contest org, which has 22,000+ records, a few hundred of which have timeseries data associated with them.

**Comment by nllong** [comment]
this should not be an issue anymore. not a clear test.

**Comment by RDmitchell** [comment]
@nllong -- do you think it's worth testing? We don't really deal with time series data anymore so I wouldn't know what data set to test for this ... Or maybe you can suggest a test file (or the type of file that would test this?)

**Comment by nllong** [comment]
I am going to close. There is no easy way to test at the moment.

**Comment by RDmitchell** [comment]
agreed. thx
